"""SYNTHETIC demonstration fixtures — never live data.

Written only to the separate data_demo/ directory; the warehouse meta key `mode` is DEMO_SYNTHETIC, every
series carries metadata synthetic=true and an attribution of "SYNTHETIC DEMO DATA", headlines use the
reserved `.invalid` domain and a "[DEMO]" prefix, and exports carry a watermark.
"""
from __future__ import annotations

import json
from datetime import date, datetime, timedelta, timezone

import numpy as np

from .collectors.news import upsert_headline
from .pipeline import analyse_wh, make_context
from .settings import get_paths
from .storage.warehouse import Warehouse

ATTR = "SYNTHETIC DEMO DATA — generated by oco.demo, not a real source"


def build(seed: int = 7):
    paths = get_paths(demo=True)
    if paths.warehouse.exists():
        paths.warehouse.unlink()
    ctx = make_context(paths)
    rng = np.random.default_rng(seed)
    end = date.today() - timedelta(days=3)
    days = [end - timedelta(days=i) for i in range(900)][::-1]
    with Warehouse.writer(paths) as wh:
        wh.set_meta("mode", "DEMO_SYNTHETIC")
        sha = wh.store_raw("demo", json.dumps({"generator": "oco.demo", "seed": seed}).encode(), url="synthetic://oco.demo",
                           content_type="application/json", ext="json", note="SYNTHETIC")

        def series(sid, name, unit, freq, rows, source, geo_, product, extra=None):
            wh.upsert_series(sid, source=source, source_key=sid, name=name, geography=geo_, product=product, unit=unit,
                             frequency=freq, description="SYNTHETIC", metadata={"synthetic": True, "attribution": ATTR, **(extra or {})})
            wh.ingest_observations(sid, rows, raw_sha256=sha)

        brent, fx = [], []
        p, f = 75.0, 1.10
        for i, d in enumerate(days):
            if d.weekday() >= 5:
                continue
            p *= float(np.exp(rng.normal(0, 0.017) + (0.09 if i == len(days) - 6 else 0)))
            f *= float(np.exp(rng.normal(0, 0.003)))
            brent.append({"obs_start": d, "obs_end": d, "value": round(p, 2)})
            fx.append({"obs_start": d, "obs_end": d, "value": round(f, 4)})
        series("eia.brent_spot", "Brent spot price FOB (SYNTHETIC)", "USD per barrel", "daily", brent, "EIA", "Europe (North Sea)", "crude_brent")
        series("ecb.usd_per_eur", "USD per EUR (SYNTHETIC)", "USD per EUR", "daily", fx, "ECB", "Euro area", "fx")
        tank = []
        for i, d in enumerate(days[:-4]):  # provider lag: last 4 days not yet published
            base = 38 + 4 * np.sin(i / 58) - (2 if d.weekday() == 4 else 0)
            v = rng.poisson(max(base - (16 if i > len(days) - 20 else 0), 1))
            missing = i in (len(days) - 40, len(days) - 39)
            tank.append({"obs_start": d, "obs_end": d, "value": None if missing else float(v)})
        series("portwatch.hormuz.n_tanker", "Strait of Hormuz: tanker transit calls (SYNTHETIC)",
               "vessel transits per day (AIS transit calls, not barrels)", "daily", tank, "IMF PortWatch", "Strait of Hormuz", "shipping",
               {"limitations": ["SYNTHETIC", "tanker transits are not barrels"]})
        mondays = [d for d in days if d.weekday() == 0]
        for cc, lvl in (("DE", 1.70), ("EU", 1.65)):
            wt, wo = [], []
            x = lvl
            for d in mondays:
                x += float(rng.normal(0, 0.012))
                pre = x - 0.95
                wt.append({"obs_start": d, "obs_end": d, "value": round(x, 3)})
                wo.append({"obs_start": d, "obs_end": d, "value": round(pre, 3)})
            for tax, rows in (("with_tax", wt), ("without_tax", wo)):
                series(f"oil_bulletin.{cc}.diesel.{tax}", f"{cc} automotive diesel {tax.replace('_', ' ')} (SYNTHETIC)", "EUR per litre",
                       "weekly", rows, "EU Oil Bulletin", cc, "diesel")
        fridays = [d for d in days if d.weekday() == 4]
        st, s = [], 430000.0
        for d in fridays:
            s += float(rng.normal(0, 3500))
            st.append({"obs_start": d, "obs_end": d, "value": round(s)})
        series("eia.us_commercial_crude_stocks", "US commercial crude stocks (SYNTHETIC)", "thousand barrels", "weekly", st, "EIA", "US", "crude",
               {"measure": "stock"})
        now = datetime.now(timezone.utc)
        for title, delta in (("[DEMO] Oil prices surge as Hormuz tanker traffic slows", 5),
                             ("[DEMO] Dieselpreise steigen deutlich", 2),
                             ("[DEMO] Strait of Hormuz shipping disrupted, insurers say", 12)):
            upsert_headline(wh, url=f"https://demo.invalid/{abs(hash(title)) % 10**8}", title=title, publisher="DEMO (synthetic)",
                            language="en", published_at=now - timedelta(days=delta), published_at_source="synthetic",
                            discovered_at=now - timedelta(days=delta), discovery_source="demo", origin="demo")
        analyse_wh(ctx, wh)
    return paths.data
